source c:\code\mysqldalg\malg\src\main\resources\DatabaseSchema\stored_procs\extra_column_test.sql
source c:\code\mysqldalg\malg\src\main\resources\DatabaseSchema\stored_procs\insert_basictypes_return_saved_values.sql
source c:\code\mysqldalg\malg\src\main\resources\DatabaseSchema\stored_procs\insert_char_1_return_saved_value.sql
source c:\code\mysqldalg\malg\src\main\resources\DatabaseSchema\stored_procs\insert_char_255_return_saved_value.sql
source c:\code\mysqldalg\malg\src\main\resources\DatabaseSchema\stored_procs\insert_char_5_return_saved_value.sql
source c:\code\mysqldalg\malg\src\main\resources\DatabaseSchema\stored_procs\insert_data_return_saved_values_with_extra_column.sql
source c:\code\mysqldalg\malg\src\main\resources\DatabaseSchema\stored_procs\insert_tinyblob_return_saved_value.sql
source c:\code\mysqldalg\malg\src\main\resources\DatabaseSchema\stored_procs\insert_varchar_5000_return_saved_value.sql
source c:\code\mysqldalg\malg\src\main\resources\DatabaseSchema\stored_procs\insert_varchar_500_return_saved_value.sql
source c:\code\mysqldalg\malg\src\main\resources\DatabaseSchema\stored_procs\insert_varchar_50_return_saved_value.sql
source c:\code\mysqldalg\malg\src\main\resources\DatabaseSchema\stored_procs\omitted_column_test_middle.sql
source c:\code\mysqldalg\malg\src\main\resources\DatabaseSchema\stored_procs\testbasictypes.sql
source c:\code\mysqldalg\malg\src\main\resources\DatabaseSchema\stored_procs\test_blob_tinyblob.sql
source c:\code\mysqldalg\malg\src\main\resources\DatabaseSchema\stored_procs\test_char_1.sql
source c:\code\mysqldalg\malg\src\main\resources\DatabaseSchema\stored_procs\test_char_255.sql
source c:\code\mysqldalg\malg\src\main\resources\DatabaseSchema\stored_procs\test_char_5.sql
source c:\code\mysqldalg\malg\src\main\resources\DatabaseSchema\stored_procs\test_varchar_50.sql
source c:\code\mysqldalg\malg\src\main\resources\DatabaseSchema\stored_procs\test_varchar_500.sql
source c:\code\mysqldalg\malg\src\main\resources\DatabaseSchema\stored_procs\test_varchar_5000.sql
