DELIMITER $$

DROP PROCEDURE IF EXISTS `testbasictypes` $$
CREATE DEFINER=`malg`@`%` PROCEDURE `testbasictypes`(
  in p_type_big_int_null bigint,
  in p_type_big_int_not_null bigint,
  in p_type_decimal_null decimal(10,2),
  in p_type_decimal_not_null decimal(10,2),
  in p_type_double_null double,
  in p_type_double_not_null double,
  in p_type_float_null float,
  in p_type_float_not_null float,
  in p_type_int_null int,
  in p_type_int_not_null int,
  in p_type_mediumint_null mediumint,
  in p_type_mediumint_not_null mediumint,
  in p_type_smallint_null smallint,
  in p_type_smallint_not_null smallint,
  in p_type_tinyint_null tinyint,
  in p_type_tinyint_not_null tinyint,
  in p_type_char_null char,
  in p_type_char_not_null char,
  in p_type_varchar_45_null varchar(45),
  in p_type_varchar_45_not_null varchar(45),
  in p_type_date_null date,
  in p_type_date_not_null date,
  in p_type_datetime_null datetime,
  in p_type_datetime_not_null datetime,
  in p_type_time_null time,
  in p_type_time_not_null time,
  in p_type_timestamp_null timestamp ,
  in p_type_timestamp_not_null timestamp,
  in p_type_year_null year,
  in p_type_year_not_null year,
  in p_type_longtext_null longtext,
  in p_type_longtext_not_null longtext,
  in p_type_mediumtext_null mediumtext,
  in p_type_mediumtext_not_null mediumtext,
  in p_type_text_null text,
  in p_type_text_not_null text,
  in p_type_tinytext_null tinytext,
  in p_type_tinytext_not_null tinytext,
  in p_type_bit_null bit(1),
  in p_type_bit_not_null bit(1),
  in p_type_enum_not_null enum('true','false'),
  in p_type_enum2_not_null enum('male', 'female')
)
BEGIN
-- proxy:Test:
-- returns:alltypes:1

	INSERT INTO malgtest.alltypes
		(type_big_int_null,
		type_big_int_not_null,
		type_decimal_null,
		type_decimal_not_null,
		type_double_null,
		type_double_not_null,
		type_float_null,
		type_float_not_null,
		type_int_null,
		type_int_not_null,
		type_mediumint_null,
		type_mediumint_not_null,
		type_smallint_null,
		type_smallint_not_null,
		type_tinyint_null,
		type_tinyint_not_null,
		type_char_null,
		type_char_not_null,
		type_varchar_45_null,
		type_varchar_45_not_null,
		type_date_null,
		type_date_not_null,
		type_datetime_null,
		type_datetime_not_null,
		type_time_null,
		type_time_not_null,
		type_timestamp_null,
		type_timestamp_not_null,
		type_year_null,
		type_year_not_null,
		type_longtext_null,
		type_longtext_not_null,
		type_mediumtext_null,
		type_mediumtext_not_null,
		type_text_null,
		type_text_not_null,
		type_tinytext_null,
		type_tinytext_not_null,
		type_bit_null,
		type_bit_not_null,
		type_enum_not_null,
		type_enum2_not_null)
	VALUES
		(p_type_big_int_null,
		p_type_big_int_not_null,
		p_type_decimal_null,
		p_type_decimal_not_null,
		p_type_double_null,
		p_type_double_not_null,
		p_type_float_null,
		p_type_float_not_null,
		p_type_int_null,
		p_type_int_not_null,
		p_type_mediumint_null,
		p_type_mediumint_not_null,
		p_type_smallint_null,
		p_type_smallint_not_null,
		p_type_tinyint_null,
		p_type_tinyint_not_null,
		p_type_char_null,
		p_type_char_not_null,
		p_type_varchar_45_null,
		p_type_varchar_45_not_null,
		p_type_date_null,
		p_type_date_not_null,
		p_type_datetime_null,
		p_type_datetime_not_null,
		p_type_time_null,
		p_type_time_not_null,
		p_type_timestamp_null,
		p_type_timestamp_not_null,
		p_type_year_null,
		p_type_year_not_null,
		p_type_longtext_null,
		p_type_longtext_not_null,
		p_type_mediumtext_null,
		p_type_mediumtext_not_null,
		p_type_text_null,
		p_type_text_not_null,
		p_type_tinytext_null,
		p_type_tinytext_not_null,
		p_type_bit_null,
		p_type_bit_not_null,
		p_type_enum_not_null,
		p_type_enum2_not_null);

	SELECT * FROM alltypes WHERE alltypescol_id=LAST_INSERT_ID();
END $$

DELIMITER ;